#!/usr/bin/env bash
#
# render-env-from-vault.sh
#
# Renders a systemd EnvironmentFile for a service by combining:
#   1. non-secret defaults from config/services/<service>/env/<service>.env.example
#   2. secrets pulled from HashiCorp Vault, as declared in the service's
#      config/services/<service>/vault.manifest.yml
#
# The output file is written with 0600 permissions and is intended to be
# referenced by the service's systemd unit via EnvironmentFile=.
#
# Usage:
#   render-env-from-vault.sh <service> <environment> <output-file>
#
# Example:
#   VAULT_ADDR=https://vault.example.com VAULT_TOKEN=... \
#     scripts/render-env-from-vault.sh ids-platform-backend qa \
#       /opt/ids-platform-backend/ids-platform-backend.env
#
# Requirements: bash, vault CLI (authenticated via VAULT_ADDR + VAULT_TOKEN or
# any other configured auth), yq (v4, mikefarah).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

die() {
  echo "render-env-from-vault: $*" >&2
  exit 1
}

[ "$#" -eq 3 ] || die "usage: $0 <service> <environment> <output-file>"

SERVICE="$1"
ENVIRONMENT="$2"
OUTPUT="$3"

command -v vault >/dev/null 2>&1 || die "vault CLI not found in PATH"
command -v yq >/dev/null 2>&1 || die "yq (v4) not found in PATH"

SERVICE_DIR="${REPO_ROOT}/config/services/${SERVICE}"
MANIFEST="${SERVICE_DIR}/vault.manifest.yml"
BASE_ENV="${SERVICE_DIR}/env/${SERVICE}.env.example"

[ -f "${MANIFEST}" ] || die "manifest not found: ${MANIFEST}"

MOUNT="$(yq -r '.vault.mount' "${MANIFEST}")"
BASE_PATH="$(yq -r '.vault.basePath' "${MANIFEST}")"
SECRET_PATH="${BASE_PATH}/${ENVIRONMENT}"

[ "${MOUNT}" != "null" ] || die "vault.mount missing in ${MANIFEST}"
[ "${BASE_PATH}" != "null" ] || die "vault.basePath missing in ${MANIFEST}"

TMP="$(mktemp)"
trap 'rm -f "${TMP}"' EXIT

{
  echo "# Generated by render-env-from-vault.sh for ${SERVICE} (${ENVIRONMENT})."
  echo "# Non-secret defaults + secrets read from Vault path ${MOUNT}/${SECRET_PATH}."
  echo "# Do not edit by hand; regenerate on deploy."
  echo
} >"${TMP}"

# 1. Non-secret defaults (skip comments and blank lines).
if [ -f "${BASE_ENV}" ]; then
  echo "# --- non-secret defaults (${SERVICE}.env.example) ---" >>"${TMP}"
  grep -vE '^\s*(#|$)' "${BASE_ENV}" >>"${TMP}" || true
  echo >>"${TMP}"
fi

# 2. Secrets from Vault, one per manifest entry.
echo "# --- secrets from Vault (${MOUNT}/${SECRET_PATH}) ---" >>"${TMP}"
COUNT="$(yq -r '.secrets | length' "${MANIFEST}")"
for i in $(seq 0 $((COUNT - 1))); do
  ENV_VAR="$(yq -r ".secrets[$i].env" "${MANIFEST}")"
  FIELD="$(yq -r ".secrets[$i].field" "${MANIFEST}")"
  VALUE="$(vault kv get -mount="${MOUNT}" -field="${FIELD}" "${SECRET_PATH}")" \
    || die "failed to read field '${FIELD}' from ${MOUNT}/${SECRET_PATH}"
  printf '%s=%s\n' "${ENV_VAR}" "${VALUE}" >>"${TMP}"
done

install -m 0600 "${TMP}" "${OUTPUT}"
echo "render-env-from-vault: wrote ${OUTPUT} (${COUNT} secret(s) from ${MOUNT}/${SECRET_PATH})"
